### ISSUE TITLE
conf_parser.cxx:1296:36: error: ‘aConf’ was not declared in this scope

### ISSUE THREAD

**Issue by solbu** [solbu/hldig#109]
When running «make dist» something reconfigures «htcommon/conf_parser.cxx», which makes it fail build.

To test, run in this exact sequence:
./configure && make dist && make

It results in this error (I have run make a second time, isolating the build error)

> make 
> Making all in db
> make[1]: Entering directory '/home/solbu/download/git-repos/hldig/db'
> make  all-am
> make[2]: Entering directory '/home/solbu/download/git-repos/hldig/db'
> make[2]: Leaving directory '/home/solbu/download/git-repos/hldig/db'
> make[1]: Leaving directory '/home/solbu/download/git-repos/hldig/db'
> Making all in htlib
> make[1]: Entering directory '/home/solbu/download/git-repos/hldig/htlib'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/home/solbu/download/git-repos/hldig/htlib'
> Making all in htword
> make[1]: Entering directory '/home/solbu/download/git-repos/hldig/htword'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/home/solbu/download/git-repos/hldig/htword'
> Making all in htcommon
> make[1]: Entering directory '/home/solbu/download/git-repos/hldig/htcommon'
> /bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../include  -pedantic -DDEFAULT_CONFIG_FILE=\"/opt/www/etc/hldig/hldig.conf\" -I../include -I../htlib -I../htnet -I../htcommon -I../htword -I../db -I../db -DBIN_DIR=\"/opt/www/bin\" -DCOMMON_DIR=\"/opt/www/share/hldig/templates\" -DCONFIG_DIR=\"/opt/www/etc/hldig\" -DDATABASE_DIR=\"/opt/www/var/hldig\" -DIMAGE_URL_PREFIX=\"/www\"  -DLOCALEDIR=\"/opt/www/share/locale\"   -g -O2 -Wall -fno-rtti -fno-exceptions -c -o conf_parser.lo conf_parser.cxx
> libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../include -pedantic -DDEFAULT_CONFIG_FILE=\"/opt/www/etc/hldig/hldig.conf\" -I../include -I../htlib -I../htnet -I../htcommon -I../htword -I../db -I../db -DBIN_DIR=\"/opt/www/bin\" -DCOMMON_DIR=\"/opt/www/share/hldig/templates\" -DCONFIG_DIR=\"/opt/www/etc/hldig\" -DDATABASE_DIR=\"/opt/www/var/hldig\" -DIMAGE_URL_PREFIX=\"/www\" -DLOCALEDIR=\"/opt/www/share/locale\" -g -O2 -Wall -fno-rtti -fno-exceptions -c conf_parser.cxx  -fPIC -DPIC -o .libs/conf_parser.o
> conf_parser.cxx: In function ‘int yyparse()’:
> conf_parser.cxx:1296:36: error: ‘aConf’ was not declared in this scope
>                 ((HtConfiguration *)aConf)->AddParsed((yyvsp[0].ConfLine)->name,(yyvsp[0].ConfLine)->value);
>                                     ^
> conf_parser.cxx:1386:31: error: ‘aConf’ was not declared in this scope
>            ((HtConfiguration *)aConf)->Add((yyvsp[-10].str),(yyvsp[-8].str),(yyvsp[-5].ConfLines));
>                                ^
> conf_parser.cxx:1598:35: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
>        yyerror (YY_("syntax error"));
>                                    ^
> conf_parser.cxx:1742:35: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
>    yyerror (YY_("memory exhausted"));
>                                    ^
> Makefile:578: recipe for target 'conf_parser.lo' failed
> make[1]: *** [conf_parser.lo] Error 1
> make[1]: Leaving directory '/home/solbu/download/git-repos/hldig/htcommon'
> Makefile:497: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1
>

**Comment by andy5995** [comment]
I don't have any experience with bison so not sure how long it would take me to figure this out.

Another option may be: Assuming this only parses the config file, switching to a different method for parsing may be a better option. https://github.com/martinh/libconfuse

**Comment by andy5995** [comment]
conf_lexer.cxx and conf_parser.cxx needs to be removed from version control, they are auto-generated when make is run.

Makefile.am needs to be changed so those 2 files will be removed when `make clean` is run.

The bigger problem remaining is that when those two are removed, I can't build either. Therefore, we'll need to figure out how to update conf_parser.hxx and conf_lexer.lxx to get a complete build.

I'll start working on this.

**Comment by andy5995** [comment]
So the cxx files are supposed to be included with the distribution. When they get regenerated after running `make dist` or removing them, the build fails.

I believe it's because the use of YYPARSE_PARAM in conf_parser.yxx. It's obsolete

https://stackoverflow.com/questions/5676619/bison-additional-parameter-to-a-push-and-pure-parser

http://www.delorie.com/gnu/docs/bison/bison_106.html

And the modern-day equivalent is 
https://www.gnu.org/software/bison/manual/html_node/Parser-Function.html

But so far I have absolutely no idea of how to convert the code.

**Comment by solbu** [comment]
It seems the patch from NevemTeve is working. Now I get a new error.

> Making all in hlfuzzy
> make[1]: Entering directory '/home/solbu/download/git-repos/hldig/hlfuzzy'
> /bin/sh ../libtool  --tag=CXX   --mode=link g++  -g -O2 -Wall -fno-rtti -fno-exceptions    -o hlfuzzy hlfuzzy.o libfuzzy.la ../hlnet/libhlnet.la ../hlcommon/libcommon.la ../hlword/libhlword.la ../hllib/libhl.la ../db/libhldb.la -lz  -lcrypto -lssl -lcrypto
> libtool: link: g++ -g -O2 -Wall -fno-rtti -fno-exceptions -o .libs/hlfuzzy hlfuzzy.o  ./.libs/libfuzzy.so ../hlnet/.libs/libhlnet.so ../hlcommon/.libs/libcommon.so ../hlword/.libs/libhlword.so ../hllib/.libs/libhl.so ../db/.libs/libhldb.so -lz -lssl -lcrypto -Wl,-rpath -Wl,/opt/www/lib/hldig -Wl,-rpath -Wl,/opt/www/lib/hldig_db
> ../hlcommon/.libs/libcommon.so: undefined reference to `yyparse(void*)'
> collect2: error: ld returned 1 exit status
> Makefile:557: recipe for target 'hlfuzzy' failed
> make[1]: *** [hlfuzzy] Error 1
> make[1]: Leaving directory '/home/solbu/download/git-repos/hldig/hlfuzzy'
> Makefile:497: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1

**Comment by andy5995** [comment]
Note [comment 6](https://www.linuxquestions.org/questions/programming-9/converting-yyparse_param-to-parse-param-4175638020/#post5908085)
