### ISSUE TITLE
Question/request: hldig as htdig?

### ISSUE THREAD

**Issue by selkfoster** [solbu/hldig#144]
Hello @solbu,

In the Trinity project[1] we wonder[2] if it is possible for hldig to be renamed to htdig?  Perhaps you have contact with the original author and it is possible to continue as htdig, this would help avoid renaming or adding things to look for "hldig".  Incidentally, it would mean that projects that already include htdig would continue in new and improved versions.

Thanks for your work on the hldig maintenance.

[1] https://trinitydesktop.org/
[2] https://mirror.git.trinitydesktop.org/gitea/TDE/tdebase/issues/119

**Comment by solbu** [comment]
Andy Alt, the one who actually forked and launched hldig had some issues he wanted fixed, and asked the ht://Dig developers that if he would send ay patches, would they include it and do a release. They answered that he was better off forking it, as they had no more interest in the project.

So no, it will not be renamed, as we did quite a job remnaming from htdig to hldig. :-)

**Comment by solbu** [comment]
It seems one of the developers also have a Github repo of the htdig master branch.
[Here is the thread](/roklein/htdig/issues/1) where Andy communicated with one of the hldig developers, which resulted in Andy forking it, and eventually renaming it to hldig later on.
