### ISSUE TITLE
WordKeyInfo.cc:48:18: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]

### ISSUE THREAD

**Issue by ghost** [solbu/hldig#40]
Anybody interested in doing a PR for this?

`WordKeyInfo.cc:48:18: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
name.set("Word");`

**Comment by andy5995** [comment]
Now on L53

https://github.com/andy5995/htdig/blob/a4f1085be0ce03fda0f2b0338eebbaace1305c68/htword/WordKeyInfo.cc#L53

**Comment by solbu** [comment]
This is fixed with PR #135 and #134
