### ISSUE TITLE
new hl://Dig logo needed

### ISSUE THREAD

**Issue by andy5995** [solbu/hldig#56]
Because hl://Dig is a fork of ht://Dig, it should have a different logo.

Any graphic designers interested in this?

**Comment by jamessouth** [comment]
![logo](https://user-images.githubusercontent.com/25541381/37440798-5c7b0338-27cc-11e8-82da-fa6d979e748c.jpg)

here's an idea i put together real quick

**Comment by andy5995** [comment]
oh, yeah, that looks good :)

Right now, I think the logo is primarily used in hldig search results

http://htdig.dreamhosters.com/

But that could also go on the README

Thanks!

**Comment by jamessouth** [comment]
yeah that's the only place i have seen it, i ran a search just to see what happens, it took me to dreamhosters with the old logo up top. so i just threw something together that was somewhat like the old one, small, simple. i think i will tweak it a little to give the content a little padding, get the edge away a bit.

**Comment by jamessouth** [comment]
![logo3](https://user-images.githubusercontent.com/25541381/37443751-ffc35e46-27db-11e8-8152-dcae2ac0f0c7.jpg)

re-proportioned to shrink image relative to text

**Comment by andy5995** [comment]
Ok, so to make the replacement...

The files are here:

https://github.com/andy5995/hldig/tree/master/installdir

Now that I think of it, I don't think it's needed in the footer. It's not really customary to have the same logo on the top and at the bottom, is it?

So the htdig.gif can be replaced, then edit the html files in installdir/ to reflect the change. 

Then edit L10 of Makefile.am to remove htdig.gif and htdig.png and replace it with the filename of your new graphic.

The hldig.png file can be removed. I don't see that it's being used anywhere.

Or, if you'd rather just make the PR for the graphic, I will edit the other files accordingly.
