### ISSUE TITLE
`make dist` shouldn't try to build tests when creating tarball

### ISSUE THREAD

**Issue by andy5995** [solbu/hldig#91]
As reported by @solbu , `make dist` does not work.

I'll start working on that within the next few days, unless someone else wants to.

**Comment by solbu** [comment]
I fixed the most critical part of this issue.

It remains to figure out how to stop «make dist» from running the compile and tests in test/ when creating a tarball.
If one doesn't compile everything before make dist, It will fail. I've never seen that happen before.

But it's not critical at the moment.

**Comment by andy5995** [comment]
But sounds like something there should be a ticket for?

**Comment by solbu** [comment]
I believe this is fixed somewhere along the way, and issue #109 fixed the remaning bit.
